name: instagram_clone
description: An instagram clone.
publish_to: 'none'

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.4
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.7
  image_picker: ^1.0.2
  intl: ^0.18.1
  permission_handler: ^10.4.3
  provider: ^6.0.5
  uuid: ^4.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/ic_instagram.svg
